language: cpp

env:
  matrix:
   - NODE_VERSION="0.8" RUN_BUILD="static_build"
   - NODE_VERSION="0.10" RUN_BUILD="static_build"
   - NODE_VERSION="0.8" RUN_BUILD="shared_build"
   - NODE_VERSION="0.10" RUN_BUILD="shared_build"
  global:
   - secure: LvrV5lifkIM99Wz0G0jqxC3uqGYIYz4hgM0oeB0MsPmQ62l8+CfIURqcFlfKSb+0s0YP2mAeacSno8oTpSZoWP27sTJutYmyk0jeVUHKQqwQClkloeErOfyLVnYijUTAX/J1Blgl+fhfvGtZE/dBIk/XEa6tEKmF0kv7z6GKVz8=
   - secure: hNMAfx4uCD8P5ycw7en9WbPFxd9Z4i8LmuClPC6lYYBTf/3lsHbtO5oRVmqFQevlZbFoPt1OU1pr4Pnj7iQsYnezc3YBevXQNsv0UvMlQAzwmW2cQOuRjHZ5TXEEMAQBbiWO0BOeQrC6m46wkQbkuzX1XpxRnaXhdhd/FeZxVwk=
   - secure: ExeNqcXWXhCuXT4gT5EicaDUJHMw4oRu9U6++Msuw/cpKriT6181SnOHj6j+b7P+XZKcpRPRUbwUECmQ/D+ULblp63WCpvux77qxHLj0EXcnM35HfubSBAnQ548eoI292ttv2p0/naHu190z1g/OZc1nGNmUT6QfhulFFgBC57s=

before_install:
# put node-pre-gyp on path
- export PATH=./node_modules/.bin/:$PATH
- echo $NODE_VERSION
- git clone https://github.com/creationix/nvm.git ../.nvm
- source ../.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- node --version
- npm --version

install:
- CURRENT_DIR=`pwd`
- source ./util/${RUN_BUILD}.sh
- cd $CURRENT_DIR

before_script:
- npm install mocha

before_script:
- npm install --build-from-source

script:
- make test
- PUBLISH_BINARY=false
- if [ "[publish-binary]" = `git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n'` ]; then echo PUBLISH_BINARY;PUBLISH_BINARY=true; fi;
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]] && [[ $RUN_BUILD == "static_build" ]]; then echo PUBLISH_BINARY;PUBLISH_BINARY=true; fi;
- if [[ $PUBLISH_BINARY == true ]]; then node-pre-gyp package publish; fi
- if [[ $PUBLISH_BINARY == true ]]; then npm install --fallback-to-build=false; fi
# TODO - unpublish binary if this failed

after_success:
# publish to npm if this is a tag
- if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]] && [[ $RUN_BUILD == "static_build" ]] && [[ $NODE_VERSION == "0.10" ]]; then npm publish --silent --email=dane@dbsgeo.com --_auth=$NPM_AUTH; fi;