language: node_js

node_js:
 - "0.10"
 - "0.8"

env:
  matrix:
    - export RUN_BUILD="shared_build"
    - export RUN_BUILD="static_build"
  global:
    - secure: F+sEL/v56CzHqmCSSES4pEyC9NeQlkoR0Gs/ZuZxX1ytrj8SKtp3MKqBj7zhIclSdXBz4Ev966Da5ctmcTd410p0b240MV6BVOkLUtkjZJyErMBOkeb8n8yVfSoeMx8RiIhBmIvEn+rlQq+bSFis61/JkE9rxsjkGRZi14hHr4M=
    - secure: o2nkUQIiABD139XS6L8pxq3XO5gch27hvm/gOdV+dzNKc/s2KomVPWcOyXNxtJGhtecAkABzaW8KHDDi5QL1kNEFx6BxFVMLO8rjFPsMVaBG9Ks6JiDQkkmrGNcnVdxI/6EKTLHTH5WLsz8+J7caDBzvKbEfTux5EamEhxIWgrI=

before_install:
 # fixes node/gyp install
 # https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
 - ./util/${RUN_BUILD}.sh

before_script:
 - npm install mocha

before_script:
 - npm install --verbose --build-from-source

script:
 - make test
 - if [ $RUN_BUILD == "static_build" ]; then ./node_modules/.bin/node-pre-gyp package publish; fi
