language: node_js

node_js:
 - "0.10"
 - "0.8"

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install build-essential git cmake libboost1.46-all-dev libprotoc-dev libprotobuf7 protobuf-compiler libprotobuf-dev libosmpbf-dev libpng12-dev libbz2-dev libstxxl-dev libstxxl-doc libstxxl1 libxml2-dev libzip-dev lua5.1 liblua5.1-0-dev libluabind-dev
 - git clone https://github.com/scrosby/OSM-binary.git
 - cd OSM-binary/src
 - make && sudo make install
 - cd ../../

install:
 - npm install mocha
 - git clone https://github.com/DennisOSRM/Project-OSRM.git ../Project-OSRM
 - cd ../Project-OSRM
 - git checkout develop
 - mkdir -p build && cd build && cmake ../ -DWITH_TOOLS=1
 - make
 - cd ../../node-OSRM

before_script:
 - export CXXFLAGS="-I/usr/include/lua5.1/"
 - npm install

script:
 - make test # make target downloads data and prepares it if it does not exist
