language: node_js

node_js:
 - "0.10"
 - "0.8"

env:
  matrix:
    - export RUN_BUILD="shared_build"
    - export RUN_BUILD="static_build"
  global:
    - secure: LvrV5lifkIM99Wz0G0jqxC3uqGYIYz4hgM0oeB0MsPmQ62l8+CfIURqcFlfKSb+0s0YP2mAeacSno8oTpSZoWP27sTJutYmyk0jeVUHKQqwQClkloeErOfyLVnYijUTAX/J1Blgl+fhfvGtZE/dBIk/XEa6tEKmF0kv7z6GKVz8=
    - secure: hNMAfx4uCD8P5ycw7en9WbPFxd9Z4i8LmuClPC6lYYBTf/3lsHbtO5oRVmqFQevlZbFoPt1OU1pr4Pnj7iQsYnezc3YBevXQNsv0UvMlQAzwmW2cQOuRjHZ5TXEEMAQBbiWO0BOeQrC6m46wkQbkuzX1XpxRnaXhdhd/FeZxVwk=

before_install:
 # fixes node/gyp install
 # https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
 - ./util/${RUN_BUILD}.sh

before_script:
 - npm install mocha

before_script:
 - npm install --verbose --build-from-source

script:
 - make test
 - if [ $RUN_BUILD == "static_build" ]; then ./node_modules/.bin/node-pre-gyp package publish; fi
